In [123]:
import pandas as pd

In [124]:
#To read dataset
df = pd.read_csv("SMS fraud Dataset.csv")
df.head()

                                                 sms  label
0  Go until jurong point, crazy.. Available only ...      0
1                    Ok lar... Joking wif u oni...\n      0
2  Free entry in 2 a wkly comp to win FA Cup fina...      1
3  U dun say so early hor... U c already then say...      0
4  Nah I don't think he goes to usf, he lives aro...      0

In [125]:
#Here, we see label is out output: where 0=>not spam, 1=>spam

In [126]:
#To check the shape
df.shape

(5573, 2)

In [127]:
df['sms'].head(1)

0    Go until jurong point, crazy.. Available only ...
Name: sms, dtype: object

# cleaning Text

In [128]:
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

In [129]:
def clean_text(text):
    #1.convert text to lower case
    text = text.lower()
    
    #2.Remove special characters and digits
    text = re.sub(r'[^a-zA-Z\s]','',text)
    
    #Remove link (optional only if you have links)
    text = re.sub(r'http\S+','',text)
  
    
    #3.Tokenize the text
    words = word_tokenize(text)
    
    #4. Remove stopwords
    stop_words = set(stopwords.words('english'))#{'is','an','this',..........conjunctions}
    filter_stopwords = [word for word in words if word not in stop_words]
    
    
    #5. Stemming (PorterStemmer()) : running->run,loving->love,driven ->drive
    stemmer = PorterStemmer()
    stemmed_words = [stemmer.stem(word) for word in filter_stopwords]
    
    
    #6. Finally, join the stemmed words back into a single string
    cleaned_text = ' '.join(stemmed_words)
    return cleaned_text


test_text = "This is my SMS Please chick it 9876543 %#$@&%% https://coderameen.com"
clean_text(test_text)

'sm pleas chick'

In [130]:
'''
[^a-zA-Z\s]
Explanation:
^ inside brackets negates the set.

a-zA-Z allows all English letters.

\s allows whitespace (spaces, tabs, etc.).

So [^a-zA-Z\s] matches anything that is not a letter or whitespace.


----------------------------------------
#r'http\S+':
#r'': A raw string so that backslashes (\) are treated literally in regex.

# http: Matches the literal string 'http'.

# \S: Matches any non-whitespace character (uppercase S means not space).

# \S+: Matches one or more non-whitespace characters (i.e., the rest of the URL).

# So, http\S+ matches:

# http://example.com

# https://coderameen.com

# http123456
'''

"\n[^a-zA-Z\\s]\nExplanation:\n^ inside brackets negates the set.\n\na-zA-Z allows all English letters.\n\n\\s allows whitespace (spaces, tabs, etc.).\n\nSo [^a-zA-Z\\s] matches anything that is not a letter or whitespace.\n\n\n----------------------------------------\n#r'http\\S+':\n#r'': A raw string so that backslashes (\\) are treated literally in regex.\n\n# http: Matches the literal string 'http'.\n\n# \\S: Matches any non-whitespace character (uppercase S means not space).\n\n# \\S+: Matches one or more non-whitespace characters (i.e., the rest of the URL).\n\n# So, http\\S+ matches:\n\n# http://example.com\n\n# https://coderameen.com\n\n# http123456\n"

In [131]:
df['clean_text'] = df['sms'].apply(lambda x:clean_text(x))

In [132]:
df.head()

,sms,label,clean_text
0,"Go until jurong point, crazy.. Available only ...",0,go jurong point crazi avail bugi n great world...
1,Ok lar... Joking wif u oni...\n,0,ok lar joke wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,1,free entri wkli comp win fa cup final tkt st m...
3,U dun say so early hor... U c already then say...,0,u dun say earli hor u c alreadi say
4,"Nah I don't think he goes to usf, he lives aro...",0,nah dont think goe usf live around though

In [133]:
# let check balance or imbalance
df['label'].value_counts()

0    4826
1     747
Name: label, dtype: int64

In [134]:
#Its an imbalanced dataset, lead to provide wrong outcomes!!
#Please Balance it!!
#!pip install imbalanced-learn

In [135]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\users\csc\anaconda3\lib\site-packages (0.12.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\csc\anaconda3\lib\site-packages (from imbalanced-learn) (1.9.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\csc\anaconda3\lib\site-packages (from imbalanced-learn) (1.5.1)
Requirement already satisfied: numpy>=1.17.3 in c:\users\csc\anaconda3\lib\site-packages (from imbalanced-learn) (1.23.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\csc\anaconda3\lib\site-packages (from imbalanced-learn) (2.2.0)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\csc\anaconda3\lib\site-packages (from imbalanced-learn) (1.0.2)

In [136]:
from imblearn.over_sampling import RandomOverSampler

In [137]:
#X and y axis split
X = df.drop('label',axis=1)
y =df['label']

In [138]:
#Apply RandomOverSampler to X and y
oversampler = RandomOverSampler()
X_ros,y_ros = oversampler.fit_resample(X,y)

In [139]:
#Create a new balanced dataset
df_balanced = pd.DataFrame(X_ros, columns=X.columns)

In [140]:
df_balanced

,sms,clean_text
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,Ok lar... Joking wif u oni...\n,ok lar joke wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though
...,...,...
9647,We tried to call you re your reply to our sms ...,tri call repli sm video mobil min unlimit text...
9648,You are being contacted by our Dating Service ...,contact date servic someon know find call mobi...
9649,Dear Subscriber ur draw 4 £100 gift voucher wi...,dear subscrib ur draw gift voucher b enter rec...
9650,XMAS Prize draws! We are trying to contact U. ...,xma prize draw tri contact u today draw show p...
9651,For ur chance to win a £250 wkly shopping spre...,ur chanc win wkli shop spree txt shop tsc wwwt...

In [141]:
df_balanced['label'] = y_ros

In [142]:
df_balanced

,sms,clean_text,label
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...,0
1,Ok lar... Joking wif u oni...\n,ok lar joke wif u oni,0
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...,1
3,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say,0
4,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though,0
...,...,...,...
9647,We tried to call you re your reply to our sms ...,tri call repli sm video mobil min unlimit text...,1
9648,You are being contacted by our Dating Service ...,contact date servic someon know find call mobi...,1
9649,Dear Subscriber ur draw 4 £100 gift voucher wi...,dear subscrib ur draw gift voucher b enter rec...,1
9650,XMAS Prize draws! We are trying to contact U. ...,xma prize draw tri contact u today draw show p...,1
9651,For ur chance to win a £250 wkly shopping spre...,ur chanc win wkli shop spree txt shop tsc wwwt...,1

In [143]:
df_balanced['label'].value_counts()

0    4826
1    4826
Name: label, dtype: int64

# convert clean text to vector(numerical form)

In [144]:
#train test split and vectorization(TF-IDF)
from sklearn.model_selection import train_test_split

X = df_balanced.drop(['label','sms'],axis=1)
y = df_balanced['label']
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [145]:
X_train

                                             clean_text
7008  pleas call custom servic repres ampm guarante ...
411                   come room point iron plan weekend
613                                         mani depend
2436                                 oh ya ya rememb da
6537  dear voucher holder claim st class airport lou...
...                                                 ...
5734  wan win meetgreet westlif u current tour unbre...
5191  ree entri weekli comp chanc win ipod txt pod g...
5390                               much fight good nite
860                             say somebodi name tampa
7270     current lead bid paus auction send custom care

[7721 rows x 1 columns]

In [146]:
X_test

                                             clean_text
4680                             sri dajst nw came home
5608  guarante latest nokia phone gb ipod mp player ...
733       lol wont feel bad use money take steak dinner
3846                                mmmm cant wait lick
5193                               sorri ill call later
...                                                 ...
8622  urgent nd attempt contact uu call b tcsbcmwcnx...
3410  what come hill monster hope great day thing r ...
8397  peopl dog area call join like mind guy arrang ...
5743                                      call freephon
4407  one regist subscrib u enter draw gb gift vouch...

[1931 rows x 1 columns]

In [167]:
#convert this text into vercorizer
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
X_test.shape

(1931, 1)

In [169]:
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train.iloc[:, 0])
X_test_tfidf = tfidf_vectorizer.transform(X_test.iloc[:, 0])

In [170]:
X_test_tfidf.shape

(1931, 6504)

In [171]:
X_train_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [172]:
X_test_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Train a Model

In [173]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [174]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train_tfidf,y_train)

RandomForestClassifier(random_state=42)

In [179]:
#accuracy score
y_pred = model.predict(X_test_tfidf)
accuracy_score(y_test,y_pred)

0.9979285344381149

In [180]:
#99% accuracy we have

# Save this Model

In [181]:
import pickle
pickle.dump(model,open("model.pkl","wb"))
pickle.dump(tfidf_vectorizer, open("tfidf_vectorizer.pkl","wb"))

# Prediction System

In [183]:
def spam_detection(text):
    input_clean_text = clean_text(text)
    #I know clean text has char please convert into vector (numberical)
    input_vectorized_text = tfidf_vectorizer.transform([input_clean_text])
    result = model.predict(input_vectorized_text)
    return result
    

#Example 
input_text = "I'm gonna be home soon and I don't want to talk to my manager at office"
prediction = spam_detection(input_text)

print("Prediction: ",prediction)

if prediction == 0:
    print("Real  Message!!")
    
else:
    print("Fraud Message!!")

Prediction:  [0]
Real  Message!!

In [184]:
input_text = "Free entry in weakly to win FA Cup final tickets 21th may 2025"
prediction = spam_detection(input_text)

In [185]:
prediction

array([1], dtype=int64)

In [ ]:
if prediction == 0:
    print("real message!!")
else:
    print("m")